Switching Guzzle build_query to Query::build
ovh/php-ovh pull request #116
Opened 2022-01-29 04:17 UTC by carsso

After Guzzle 7.2, GuzzleHttp\Psr7\build_query has been replaced by GuzzleHttp\Psr7\Query::build
cf https://github.com/guzzle/guzzle/pull/2712 & https://github.com/guzzle/psr7/pull/345

Signed-off-by: Germain Carré git@germain.sh

2022-01-29 04:18 UTC, carsso commented
Fixes #110

2022-04-05 22:39 UTC, TheHuman00 approved these changes

2022-06-22 02:25 UTC, carsso commented
I am now maintaining a fork containing this fix (among other smal things) here https://github.com/carsso/php-ovhcloud

2022-08-01 17:07 UTC, rbeuque74 approved these changes

2022-08-01 17:07 UTC, merged

2022-08-01 17:12 UTC, carsso commented
🙏🏻 thanks

2022-10-19 03:41 UTC, Matajess requested changes
T